entrypoint: /python/bin/fdk /function/func.py handler
memory: 1024
name: logisticpredictor
runtime: python3.6
schema_version: 20180708
triggers:
- name: logisticpredictor
  source: /logisticpredictor
  type: http
version: 0.0.1
